# Generated by Django 3.2.5 on 2021-07-26 10:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.TextField()),
                ('content1', models.TextField()),
                ('created_at1', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'pdf', ''])], verbose_name='画像ファイル')),
                ('sub1', models.IntegerField(choices=[(1, '文系教養科目'), (2, '英語科目'), (3, '第2外国語科目'), (4, '日本・日本文化科目'), (5, '教職科目'), (6, '広域教養科目'), (7, '理工系教養科目'), (8, '初年次理学院'), (9, '初年次工学院'), (10, '初年次物質理工学院'), (11, '初年次環境社会理工学院'), (12, '初年次情報理工学院'), (13, '初年次生命理工学院')], verbose_name='教科')),
                ('look1', models.IntegerField(default=0)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'pdf', ''])], verbose_name='画像ファイル')),
                ('grade', models.IntegerField(choices=[(1, 'B2'), (2, 'B3'), (3, 'B4')], verbose_name='学年')),
                ('sub', models.IntegerField(choices=[(1, '数学系'), (2, '物理系'), (3, '化学系'), (4, '地球惑星科学系'), (5, '機械系'), (6, '電気電子系'), (7, '情報通信系'), (8, 'システム制御系'), (9, '経営工学系'), (10, '材料系'), (11, '応用化学系'), (12, '数理・計算科学系'), (13, '情報工学系'), (14, '生命理工学系'), (15, '建築系'), (16, '土木・環境工学系'), (17, '融合理工系')], verbose_name='教科')),
                ('look', models.IntegerField(default=0)),
                ('like', models.ManyToManyField(blank=True, related_name='related_post', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
