# Generated by Django 3.2.5 on 2021-07-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post1',
            old_name='user1',
            new_name='user',
        ),
    ]
