# Generated by Django 3.2.5 on 2021-07-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_user1_post1_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post1',
            name='title1',
            field=models.TextField(max_length=100),
        ),
    ]
