# Generated by Django 3.2.5 on 2021-08-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_connection1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sub',
            field=models.IntegerField(choices=[(1, '数学系'), (2, '物理系'), (3, '化学系'), (4, '地球惑星科学系'), (5, '機械系'), (6, '電気電子系'), (7, '情報通信系'), (8, 'システム制御系'), (9, '経営工学系'), (10, '材料系'), (11, '応用化学系'), (12, '数理・計算科学系'), (13, '情報工学系'), (14, '生命理工学系'), (15, '建築系'), (16, '土木・環境工学系'), (17, '融合理工系'), (18, '英語科目'), (19, '第二外国語')], verbose_name='教科'),
        ),
    ]
