# Generated by Django 3.2.5 on 2021-08-25 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_rename_title1_post1_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post1',
            old_name='title',
            new_name='title1',
        ),
    ]
