# Generated by Django 3.2.5 on 2021-09-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_rename_title_post1_title1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='day',
            field=models.TextField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post1',
            name='day1',
            field=models.TextField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
